### ISSUE TITLE
How Can remove this type issues

### ISSUE THREAD

**Issue by sachinaston** [Rudloff/alltube#163]
Traceback (most recent call last): File "/usr/lib/python2.7/site.py", line 554, in <module> main() File "/usr/lib/python2.7/site.py", line 536, in main known_paths = addusersitepackages(known_paths) File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages user_site = getusersitepackages() File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages user_base = getuserbase() # this will also set USER_BASE File "/usr/lib/python2.7/site.py", line 237, in getuserbase USER_BASE = get_config_var('userbase') File "/usr/lib/python2.7/sysconfig.py", line 587, in get_config_var return get_config_vars().get(name) File "/usr/lib/python2.7/sysconfig.py", line 538, in get_config_vars _CONFIG_VARS['userbase'] = _getuserbase() File "/usr/lib/python2.7/sysconfig.py", line 215, in _getuserbase return env_base if env_base else joinuser("~", ".local") File "/usr/lib/python2.7/sysconfig.py", line 201, in joinuser return os.path.expanduser(os.path.join(*args)) File "/usr/lib/python2.7/posixpath.py", line 262, in expanduser userhome = pwd.getpwuid(os.getuid()).pw_dir KeyError: 'getpwuid(): uid not found: 48391'

**Comment by Rudloff** [comment]
Hello,
I will need a little more context here.
What exactly did you do? What is the URL of the video your are trying to download?
It would be easier to help you if you had filled the [issue template](https://github.com/Rudloff/alltube/blob/master/ISSUE_TEMPLATE.md).
