### ISSUE TITLE
An error occured - Traceback (most recent call last) 

### ISSUE THREAD

**Issue by ezbreaks** [Rudloff/alltube#17]
Hi, I installed this script but unfortunetly when I add the youtube link I receive this error and I didn't find how to solve it. Could you please help me with that?

An error occured

Please check the URL of your video.
Traceback (most recent call last): 
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main 
"__main__", fname, loader, pkg_name) 
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code 
exec code in run_globals 
File "./youtube-dl/__main__.py", line 16, in <module> 
File "./youtube-dl/youtube_dl/__init__.py", line 16, in <module> 
File "./youtube-dl/youtube_dl/options.py", line 8, in <module> 
File "./youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module> 
File "./youtube-dl/youtube_dl/downloader/common.py", line 9, in <module> 
File "./youtube-dl/youtube_dl/utils.py", line 25, in <module> 
File "/usr/lib/python2.7/ssl.py", line 61, in <module> 
import _ssl # if we can't import it, let the error propagate 
ImportError: /usr/lib/python2.7/lib-dynload/_ssl.i386-linux-gnu.so: symbol GENERAL_NAME_free, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference 

Thanks a lot!

**Comment by Rudloff** [comment]
Hello,

It looks like a problem with youtube-dl (the programme Altube uses to get the URL of the videos), you should report it here: https://github.com/rg3/youtube-dl/issues/new
