### ISSUE TITLE
Error 500 on Heroku build

### ISSUE THREAD

**Issue by ialexsilva** [Rudloff/alltube#262]
# Error 500 on Heroku build
## Your environment

**What is your web server (Apache, IIS, etc.)?**
Apache

**What version of AllTube are you using?**
Same of this repo

**How did you install AllTube (with Git or with a release package)?**
Git

## Steps to reproduce

1 - Deploy a new heroku site

2 - Go to you deployed website and you see the Error 500

Log:
`2020-02-20T23:57:21.471203+00:00 app[web.1]: Stack trace:
2020-02-20T23:57:21.471385+00:00 app[web.1]: #0 /app/vendor/jawira/case-converter/src/Convert.php(116): Jawira\CaseConverter\Convert->splitString()
2020-02-20T23:57:21.471571+00:00 app[web.1]: #1 /app/vendor/jawira/case-converter/src/Convert.php(166): Jawira\CaseConverter\Convert->readSnake()
2020-02-20T23:57:21.471757+00:00 app[web.1]: #2 /app/vendor/jawira/case-converter/src/Convert.php(80): Jawira\CaseConverter\Convert->readCamel()
2020-02-20T23:57:21.471933+00:00 app[web.1]: #3 /app/vendor/jawira/case-converter/src/Convert.php(56): Jawira\CaseConverter\Convert->load()
2020-02-20T23:57:21.472081+00:00 app[web.1]: #4 /app/classes/Config.php(242): Jawira\CaseConverter\Convert->__construct()
2020-02-20T23:57:21.472234+00:00 app[web.1]: #5 /app/classes/Config.php(153): Alltube\Config->getEnv()
2020-02-20T23:57:21.472356+00:00 app[web.1]: #6 /app/classes/Config.php(258): Alltube\Config->__construct()
2020-02-20T23:57:21.472462+00:00 app[web.1]: #7 /app/index.php(29): Alltube\Config::getInstance()
2020-02-20T23:57:21.472494+00:00 app[web.1]: #8 {main}
2020-02-20T23:57:21.472637+00:00 app[web.1]:   thrown in /app/vendor/jawira/case-converter/src/Convert.php on line 129
2020-02-20T23:57:21.473033+00:00 app[web.1]: 10.5.185.29 - - [20/Feb/2020:23:57:21 +0000] "GET / HTTP/1.1" 500 - "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36`

**Comment by ialexsilva** [comment]
![image](https://user-images.githubusercontent.com/6363160/74991329-6a779880-5424-11ea-9e56-ef4e8c6b05e6.png)

**Comment by ialexsilva** [comment]
Maybe its mbstring?

![image](https://user-images.githubusercontent.com/6363160/75094428-bbdd7000-5569-11ea-8f08-57f388a1aebd.png)

**Comment by Rudloff** [comment]
I am not sure why `mb_split()` is not available on Heroku with PHP 7.4.
But upgrading `jawira/case-converter` seems to fix the issue. (I think it no longer rely on `mb_split()`.)

This is fixed on the develop branch and will be fixed in the next release.

**Comment by ialexsilva** [comment]
Thanks @Rudloff
