### ISSUE TITLE
npm install with peerDependencies error

### ISSUE THREAD

**Issue by ask8** [Rudloff/alltube#72]
When I use npm install , it will die on the following message.
It seem some package conflit,  how to resolve it?

`
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-phpdocumentor@0.4.1 wants grunt@~0.4.1

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/bitnami/apache2/htdocs/alltube
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/bitnami/apache2/htdocs/alltube/npm-debug.log
npm ERR! not ok code 0
`

**Comment by Rudloff** [comment]
Hum, that's strange. It should only issue a warning, not an error:
```
npm WARN grunt-phpdocumentor@0.4.1 requires a peer of grunt@~0.4.1 but none was installed.
```

If you don't need the dev tools, you can try installing with `npm install --production`.

**Comment by ask8** [comment]
npm install --production.

same issue

below is npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '--production' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/opt/bitnami/apache2/htdocs/alltube',
5 verbose install   [ 'bower',
5 verbose install     'grunt',
5 verbose install     'grunt-cli',
5 verbose install     'grunt-contrib-cssmin',
5 verbose install     'grunt-contrib-uglify' ] ]
6 info preinstall alltube@0.5.2
7 verbose readDependencies using package.json deps
8 verbose already installed skipping bower@~1.7.1 /opt/bitnami/apache2/htdocs/alltube
9 verbose already installed skipping grunt@~1.0.1 /opt/bitnami/apache2/htdocs/alltube
10 verbose already installed skipping grunt-cli@~1.2.0 /opt/bitnami/apache2/htdocs/alltube
11 verbose already installed skipping grunt-contrib-uglify@~2.0.0 /opt/bitnami/apache2/htdocs/alltube
12 verbose already installed skipping grunt-contrib-cssmin@~1.0.0 /opt/bitnami/apache2/htdocs/alltube
13 silly resolved []
14 info build /opt/bitnami/apache2/htdocs/alltube
15 verbose linkStuff [ false, false, false, '/opt/bitnami/apache2/htdocs' ]
16 info linkStuff alltube@0.5.2
17 verbose linkBins alltube@0.5.2
18 verbose linkMans alltube@0.5.2
19 verbose rebuildBundles alltube@0.5.2
20 verbose rebuildBundles [ '.bin',
20 verbose rebuildBundles   'bower',
20 verbose rebuildBundles   'grunt',
20 verbose rebuildBundles   'grunt-cli',
20 verbose rebuildBundles   'grunt-contrib-compress',
20 verbose rebuildBundles   'grunt-contrib-cssmin',
20 verbose rebuildBundles   'grunt-contrib-uglify',
20 verbose rebuildBundles   'grunt-contrib-watch',
20 verbose rebuildBundles   'grunt-fixpack',
20 verbose rebuildBundles   'grunt-githash',
20 verbose rebuildBundles   'grunt-jslint',
20 verbose rebuildBundles   'grunt-jsonlint',
20 verbose rebuildBundles   'grunt-phpcs',
20 verbose rebuildBundles   'grunt-phpdocumentor',
20 verbose rebuildBundles   'grunt-phpunit' ]
21 info install alltube@0.5.2
22 info postinstall alltube@0.5.2
23 verbose unsafe-perm in lifecycle true
24 info prepublish alltube@0.5.2
25 error peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
25 error peerinvalid Peer grunt-phpdocumentor@0.4.1 wants grunt@~0.4.1
26 error System Linux 3.13.0-79-generic
27 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
28 error cwd /opt/bitnami/apache2/htdocs/alltube
29 error node -v v0.10.25
30 error npm -v 1.3.10
31 error code EPEERINVALID
32 verbose exit [ 1, true ]`

when I try to get a youtube link, the following message display
An error occured

Please check the URL of your video.
Traceback (most recent call last): File "vendor/rg3/youtube-dl/youtube_dl/__main__.py", line 19, in <module> youtube_dl.main() File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/__init__.py", line 434, in main _real_main(argv) File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/__init__.py", line 424, in _real_main retcode = ydl.download(all_urls) File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 1788, in download url, force_generic_extractor=self.params.get('force_generic_extractor', False)) File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info ie_result = ie.extract(url) File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract return self._real_extract(url) File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/youtube.py", line 1671, in _real_extract formats_dict=self._formats): File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 1521, in _extract_mpd_formats compat_etree_fromstring(mpd.encode('utf-8')), mpd_id, mpd_base_url, formats_dict=formats_dict) File "/opt/bitnami/apache2/htdocs/alltube/vendor/rg3/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory))) File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1465, in __init__ "No module named expat; use SimpleXMLTreeBuilder instead" ImportError: No module named expat; use SimpleXMLTreeBuilder instead

**Comment by Rudloff** [comment]
Are you using npm 1.3.10?
This is pretty old. You should really update to npm 3!
(Or you could use a [release package](https://github.com/Rudloff/alltube/releases), that doesn't require using npm.)

As for the other error, it seems you don't have the Python expat module:
```
No module named expat
```

**Comment by ask8** [comment]
I download the release version, the python is still there.
`No module named expat; use SimpleXMLTreeBuilder instead`

any advice?

**Comment by ask8** [comment]
it seems that my expat module is ok
`-rw-r--r-- 1 root root 114 Jun 22  2015 /usr/lib/python2.7/xml/parsers/expat.py
-rw-r--r-- 1 root root 248 Oct 14  2015 /usr/lib/python3.4/xml/parsers/expat.py
`

**Comment by Rudloff** [comment]
This is clearly not a bug in Alltube and I'm not a Python expert, so I can't help you, sorry.
You should seek help on Python forums.

**Comment by ask8** [comment]
Thanks

**Comment by ask8** [comment]
this issue should be python version issue, use 3.4 is normal.
